name: Typelevel.scala
description: Let the Scala compiler work for you. We provide type classes, instances, conversions, testing, supplements to the standard library, and much more.
twitter: typelevel
email: info@typelevel.org
gitter: "https://gitter.im/orgs/typelevel/rooms"
google_groups: "https://groups.google.com/group/typelevel"
baseurl: http://typelevel.org
googlemaps_apikey: "AIzaSyAgMQPpkd_Qq-NYcCggh28PaS82oG-9YoA"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
highlighter: rouge
exclude:
  ["README.md", "CNAME", "vendor", "src", "project/", "build.sbt", "posts"]
permalink: /blog/:year/:month/:day/:title.html
paginate: 10
paginate_path: "/blog/:num/"
sass:
  sass_dir: _scss
  style: compressed
future: true

gems: [jekyll-paginate]

collections:
  events:
    output: true
    permalink: /event/:year-:month-:title/
    layout: event
  projects:
    output: false
